### ISSUE TITLE
By pass cache per request.

### ISSUE THREAD

**Issue by jahead** [RasCarlito/axios-cache-adapter#68]
Hey, 

We (our team) have a need to force refresh a request based on user input, (they pull scroll a view). 

I'm purposing adding a variable to the request config. 
`ignoreCache: <true|false>` or `byPassCache <true|false>` or `forceRequest: <true|false>` 

I envision this working as.
1. skip getting items from the cache by pretending it was a cache miss.
2. request fresh data from the server
3. insert new data from the server. 

My preference is either `ignoreCache` or `forceRequest` because the cache is ignored but still utilized. 

let me know what you think.

**Comment by RasCarlito** [comment]
Hey @jahead !

This is interesting, my only concern is that it could actually be achieved using the new `invalidate` method or even by manually removing the cache from the store with `axiosInstance.cache.removeItem('key')`.

Adding yet another option seems like a bit of a burden. 🤔 

Nonetheless, I can also understand that having this easily accessible option instead of setting up a complicated `invalidate` method is quite convenient 😄

**Comment by jahead** [comment]
So the reasoning here for not removing the cache is that we still want to use the cache for the new item for future loads. We just want to conditionally break through the cache.

We considered overriding the `invalidate` function but we weren't sure creating more dependency on the sequence of when invalidate function is run was a good thing.

Yea the number of options is quickly growing. Just a means to break through the cache is a common one. I'm not sure on how one could fix this growing options problem.

Maybe giving users a onError function. Let them decide what to do with the error. *shrugs*
________________________________

**Comment by RasCarlito** [comment]
Ok sounds reasonable 😄 

I'll see how to minimize the number of parameters in v3.
