### ISSUE TITLE
cache store length returns 0?

### ISSUE THREAD

**Issue by scheung38** [RasCarlito/axios-cache-adapter#75]
Why am I getting Cache store length: 0 even though I make repeated calls to the same URL endpoint?

```
     // Create `axios-cache-adapter` instance
        const cache = setupCache({
          maxAge: 15 * 60 * 1000
        })

    // Create `axios` instance passing the newly created `cache.adapter`
        const api = axios.create({
          adapter: cache.adapter
        })

   const options = {
      method: 'post',
      url: e.headers.location,
      withCredentials: true,
      crossDomain: true,
      data: qs.stringify({ i: params.i }),
      headers: {
        Authorization: ''.concat('Bearer ', token),
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    }
 
    const wes = await api(options)
    console.log('wes is :', wes.data)

    // `response.request` will contain the origin `axios` request object
    assert.ok(wes.request.fromCache !== true)

    // Interacting with the store, see `localForage` API.
    const length = await cache.store.length()

    console.log('Cache store length:', length)  // <--- Cache store length: 0 ???
```

This implies I am not using cache at all? Using axios at the moment for a redirect application, but the sluggishness is difficult to handle, and was hoping this would help but at the moment it is not improving at all? Could this be more related to how I am doing a direct? as I have a list of content but each click on this large list of items, takes about 1 min to update...Any ideas?

**Comment by RasCarlito** [comment]
Hi @scheung38 !

I see that you are making a `POST` request.

For now `axios-cache-adapter` only caches `GET` requests and it clears cache for a given url when anything but a `GET` request is made to that same url.

I am working on providing more flexible options so that other than `GET` requests can be cached but it is not yet ready sorry.

[Here you can see](https://github.com/RasCarlito/axios-cache-adapter/blob/master/src/request.js#L19) that requests other than `GET` are excluded from cache.

The default cache `invalidate` method also clears the cache when requests other than `GET` are made to a given url.

Cheers

**Comment by RasCarlito** [comment]
Closing this. Caching `post` requests will be available in v3. Feel free to re-open if needed.
